
entity_browser.browser.display.exo_modal:
  type: mapping
  label: 'eXo Modal display configuration'
  mapping:
    width:
      type: string
      label: 'eXo Modal width'
    height:
      type: string
      label: 'eXo Modal height'
    link_text:
      type: string
      label: 'Link text'
    auto_open:
      type: boolean
      label: 'Auto open'
