version: "3.7"

# will use the default driver which should be "bridge"; if run via stack,
# will be a load-balanced overlay network
networks:
  ash-net:
    external: true

# will use the default driver which should be "local"
volumes:
  data-db:
    labels:
      com.augustash.keep: true

services:
  database:
    image: mariadb:10.2.25
    networks:
      - ash-net
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - data-db:/var/lib/mysql
      - ./docker/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf:ro
    env_file:
      - .env

  redis:
    image: redis:5.0.9-alpine
    networks:
      - ash-net
    ports:
      - "${CACHE_PORT:-6379}:6379"
    volumes:
      - ./docker/redis/volatile.conf:/usr/local/etc/redis/redis.conf:ro
    command:
      - /usr/local/etc/redis/redis.conf

  mailhog:
    image: augustash/alpine-mailhog:3.0.0
    networks:
      - ash-net
    ports:
      - "${MAILHOG_PORT:-1025}:1025"
      - "${MAILHOG_WEB_PORT:-8025}:8025"
    environment:
      - PUID=501
      - PGID=1000
