exo_site_settings.exo_site_settings_type.*:
  type: config_entity
  label: 'config page type config'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    aggregate:
      type: boolean
      label: 'Aggregate'
